sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script: ant